### PR TITLE
Update refinerycms-elasticsearch.gemspec

### PR DESCRIPTION
**Pull request by jitscar**
change version elasticsearch to 3.0.0

### CODE REVIEW

**Comment by bricesanchez** [comment]
It's still a good PR :)

**Comment by datenimperator** [comment]
This PR referenced 3.x last year when I wasn't ready to try this (the project where this originated is still on 2.1). I'm fine with it today.

**Comment by bricesanchez** [comment]
great :)

**Comment by bricesanchez** [comment]
You could create a 2-1-stable branch, to keep the dependecy to 2.1.x

**Comment by bricesanchez** [comment]
I've updated #5 to include #3. No needs to fix conflicts

**Comment by datenimperator** [comment]
I've merged the other one, so I assume this is obsolete?

**Pull request closed without merging**
