### PR TITLE
Remove acts_as_indexed search override of views

### PR DESCRIPTION
**Pull request by bricesanchez**
Elasticsearch in backend is not yet implemented and it currently breaks Refinery backend search.

### CODE REVIEW

**Comment by bricesanchez** [comment]
up :)

**Comment by bricesanchez** [comment]
:up: :)

**Comment by bricesanchez** [comment]
Hello @datenimperator ! Could you merge this PR ? 
Just in case you have no time to support this extension : could you consider to transfert this repo to https://github.com/refinerycms-contrib/ ?, i could add you to the org too.

**Comment by datenimperator** [comment]
@bricesanchez I'm fine with moving this into `refinerycms-contrib` which would make PRs much easier to deal with. How can we do this?

**Comment by bricesanchez** [comment]
@datenimperator Nice! Thank you for your repo transfer!

**Comment by datenimperator** [comment]
You're welcome. I'd appreciate if you could help me improve the specs for this. I find it particularly hard to test this in the context of a Refinery CMS app. Is there some source code I could read to understand how it's done w/ Refinery 3.x?

**Comment by bricesanchez** [comment]
I've never created tests for an extension with elasticsearch capabilities but i think we should open an issue to keep it in mind.

**Pull request merged**
